version: '3.9'


services:
  rabbitmq: 
    image: rabbitmq
    ports:
      - '5672:5672'
  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
    env_file:
      - ./apps/gateway/.env
    depends_on:
      - rabbitmq
      - auth
      - meetup
    ports:
      - '3000:3000'
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    env_file:
      - ./apps/auth/.env
    depends_on:
      - pg_auth
      - rabbitmq
    ports:
      - '3001:3000'
  meetup:
    build:
      context: .
      dockerfile: ./apps/meetup/Dockerfile
    env_file:
      - ./apps/meetup/.env
    links:
      - pg_meetup
    depends_on:
      - rabbitmq
    ports:
      - '3002:3000'
  pg_auth:
    container_name: pg_auth
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_DB=user
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5430:5432'
    volumes:
      - user_db_data:/var/lib/postgresql/data
  pg_meetup:
    container_name: pg_meetup
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_DB=meetup
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5431:5432'
    volumes:
      - meetup_db_data:/var/lib/postgresql/data
volumes:
  meetup_db_data:
  user_db_data: